-- Script SQL pour créer la table CIRCUIT et modifier la table VEHICULE

-- Créer la table CIRCUIT
CREATE TABLE CIRCUIT (
    ID_CIRCUIT NUMBER(*,0) PRIMARY KEY,
    NOM_CIRCUIT VARCHAR2(100 BYTE) NOT NULL,
    DESCRIPTION VARCHAR2(500 BYTE),
    DISTANCE NUMBER(10,2),
    DUREE_ESTIMEE NUMBER(*,0), -- en minutes
    DIFFICULTE VARCHAR2(20 BYTE), -- Facile, Moyen, Difficile
    IMMATRICULE VARCHAR2(50 BYTE),
    CONSTRAINT FK_CIRCUIT_VEHICULE FOREIGN KEY (IMMATRICULE) 
        REFERENCES VEHICULE(IMMATRICULE) ON DELETE CASCADE
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM";

-- Créer un index sur IMMATRICULE pour améliorer les performances
CREATE INDEX IDX_CIRCUIT_IMMATRICULE ON CIRCUIT(IMMATRICULE);

COMMIT;


