--------------------------------------------------------
--  Fichier cr�� - dimanche-novembre-09-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CIRCUIT
--------------------------------------------------------

  CREATE TABLE "DRIVINGSCHOOL"."CIRCUIT" 
   (	"ID_CIRCUIT" NUMBER, 
	"NOM_CIRCUIT" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"DISTANCE" FLOAT(126), 
	"DUREE_ESTIMEE" NUMBER, 
	"IMMATRICULE" VARCHAR2(20 BYTE), 
	"DIFFICULTE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "DRIVINGSCHOOL"."CLIENT" 
   (	"ID_CLIENT" NUMBER(*,0), 
	"NOM_CLIENT" VARCHAR2(50 BYTE), 
	"PRENOM_CLIENT" VARCHAR2(50 BYTE), 
	"CIN_CLIENT" VARCHAR2(20 BYTE), 
	"DATE_NAISSANCE" DATE, 
	"ADRESSE" VARCHAR2(100 BYTE), 
	"CODE_QR" VARCHAR2(50 BYTE), 
	"COLUMN8" VARCHAR2(50 BYTE), 
	"TEL_CLIENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
--  GPS columns for CLIENT (add if not present)
--------------------------------------------------------

ALTER TABLE "DRIVINGSCHOOL"."CLIENT"
  ADD (
    "LATITUDE"  NUMBER(10,6),
    "LONGITUDE" NUMBER(10,6)
  );
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "DRIVINGSCHOOL"."EMPLOYE" 
   (	"ID_EMPLOYE" NUMBER(*,0), 
	"NOM_EMPLOYE" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"POSTE" VARCHAR2(50 BYTE), 
	"MOT_DE_PASSEE" VARCHAR2(50 BYTE), 
	"TEL_EMPLOYE" VARCHAR2(50 BYTE), 
	"DATE_EMBAUCHE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MONITEUR
--------------------------------------------------------

  CREATE TABLE "DRIVINGSCHOOL"."MONITEUR" 
   (	"ID_MONITEUR" NUMBER(*,0), 
	"CIN_MONITEUR" VARCHAR2(20 BYTE), 
	"NOM_MONITEUR" VARCHAR2(20 BYTE), 
	"PRENOM_MONITEUR" VARCHAR2(20 BYTE), 
	"TEL_MONITEUR" NUMBER(*,0), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PERMIS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PLANIFIER
--------------------------------------------------------

  CREATE TABLE "DRIVINGSCHOOL"."PLANIFIER" 
   (	"ID_EMPLOYE" NUMBER(*,0), 
	"ID_SEANCE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SEANCE
--------------------------------------------------------

  CREATE TABLE "DRIVINGSCHOOL"."SEANCE" 
   (	"ID_SEANCE" NUMBER(*,0), 
	"IMMATRICULE" VARCHAR2(50 BYTE), 
	"ID_CLIENT" NUMBER(*,0), 
	"ID_MONITEUR" NUMBER(*,0), 
	"DATE_SEANCE" DATE, 
	"HEURE_DEBUT" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"APPAREIL" VARCHAR2(20 BYTE), 
	"DUREE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEHICULE
--------------------------------------------------------

  CREATE TABLE "DRIVINGSCHOOL"."VEHICULE" 
   (	"IMMATRICULE" VARCHAR2(50 BYTE), 
	"MODELE" VARCHAR2(20 BYTE), 
	"TYPE_VEHICULE" VARCHAR2(20 BYTE), 
	"TRANSMISSION" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"DATE_ASSURENCE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DRIVINGSCHOOL.CIRCUIT
SET DEFINE OFF;
Insert into DRIVINGSCHOOL.CIRCUIT (ID_CIRCUIT,NOM_CIRCUIT,DESCRIPTION,DISTANCE,DUREE_ESTIMEE,IMMATRICULE,DIFFICULTE) values (2,'Circuit Montagne','Parcours en altitude',35.200000000000003,96,'200TU5678','Moyen');
Insert into DRIVINGSCHOOL.CIRCUIT (ID_CIRCUIT,NOM_CIRCUIT,DESCRIPTION,DISTANCE,DUREE_ESTIMEE,IMMATRICULE,DIFFICULTE) values (3,'circuit','parrr',32.5,60,'200TU5678','Moyen');
REM INSERTING into DRIVINGSCHOOL.CLIENT
SET DEFINE OFF;
Insert into DRIVINGSCHOOL.CLIENT (ID_CLIENT,NOM_CLIENT,PRENOM_CLIENT,CIN_CLIENT,DATE_NAISSANCE,ADRESSE,COLUMN8,TEL_CLIENT) values (15,'mejri','ryhem','12345678',to_date('01-01-00','DD-MM-RR'),'aaaa','uuu@kk.com',12345678);
Insert into DRIVINGSCHOOL.CLIENT (ID_CLIENT,NOM_CLIENT,PRENOM_CLIENT,CIN_CLIENT,DATE_NAISSANCE,ADRESSE,COLUMN8,TEL_CLIENT) values (5,'moemen','kochbati','78456324',to_date('15-10-15','DD-MM-RR'),'sidi_thbet','azerty@pp.com',12345678);
Insert into DRIVINGSCHOOL.CLIENT (ID_CLIENT,NOM_CLIENT,PRENOM_CLIENT,CIN_CLIENT,DATE_NAISSANCE,ADRESSE,COLUMN8,TEL_CLIENT) values (13,'rihem','mejri','12345678',to_date('01-01-00','DD-MM-RR'),'azerty','rihem@mejri.com',12345678);
Insert into DRIVINGSCHOOL.CLIENT (ID_CLIENT,NOM_CLIENT,PRENOM_CLIENT,CIN_CLIENT,DATE_NAISSANCE,ADRESSE,COLUMN8,TEL_CLIENT) values (14,'chayma','melkiii','56124789',to_date('07-11-25','DD-MM-RR'),'chayma','chaima@melki.com',27396388);
REM INSERTING into DRIVINGSCHOOL.EMPLOYE
SET DEFINE OFF;
Insert into DRIVINGSCHOOL.EMPLOYE (ID_EMPLOYE,NOM_EMPLOYE,PRENOM,POSTE,MOT_DE_PASSEE,TEL_EMPLOYE,DATE_EMBAUCHE) values (1,'ryhemmm','mejri','hotel','azertyyy','+216azerty',to_date('01-01-00','DD-MM-RR'));
Insert into DRIVINGSCHOOL.EMPLOYE (ID_EMPLOYE,NOM_EMPLOYE,PRENOM,POSTE,MOT_DE_PASSEE,TEL_EMPLOYE,DATE_EMBAUCHE) values (2,'mohamed','hichri','directeur','123456','+21627396388',to_date('19-11-05','DD-MM-RR'));
REM INSERTING into DRIVINGSCHOOL.MONITEUR
SET DEFINE OFF;
Insert into DRIVINGSCHOOL.MONITEUR (ID_MONITEUR,CIN_MONITEUR,NOM_MONITEUR,PRENOM_MONITEUR,TEL_MONITEUR,EMAIL,PERMIS) values (5,null,null,null);
Insert into DRIVINGSCHOOL.MONITEUR (ID_MONITEUR,CIN_MONITEUR,NOM_MONITEUR,PRENOM_MONITEUR,TEL_MONITEUR,EMAIL,PERMIS) values (2,'gfdsqaz','ryhem','mejri',21365478,'mmmffnh�@fjjff.com','b');
REM INSERTING into DRIVINGSCHOOL.PLANIFIER
SET DEFINE OFF;
REM INSERTING into DRIVINGSCHOOL.SEANCE
SET DEFINE OFF;
Insert into DRIVINGSCHOOL.SEANCE (ID_SEANCE,IMMATRICULE,ID_CLIENT,ID_MONITEUR,DATE_SEANCE,HEURE_DEBUT,TYPE,APPAREIL,DUREE) values (55,'AZERTY',5,2,to_date('04-11-25','DD-MM-RR'),'03:00','Conduite','voiture',7);
Insert into DRIVINGSCHOOL.SEANCE (ID_SEANCE,IMMATRICULE,ID_CLIENT,ID_MONITEUR,DATE_SEANCE,HEURE_DEBUT,TYPE,APPAREIL,DUREE) values (25,'abc',14,2,to_date('07-11-25','DD-MM-RR'),'19:50','code','pc',2);
Insert into DRIVINGSCHOOL.SEANCE (ID_SEANCE,IMMATRICULE,ID_CLIENT,ID_MONITEUR,DATE_SEANCE,HEURE_DEBUT,TYPE,APPAREIL,DUREE) values (3,'abc',5,2,to_date('04-11-25','DD-MM-RR'),'09:36','Parc','voiture',8);
Insert into DRIVINGSCHOOL.SEANCE (ID_SEANCE,IMMATRICULE,ID_CLIENT,ID_MONITEUR,DATE_SEANCE,HEURE_DEBUT,TYPE,APPAREIL,DUREE) values (5,'abc',5,2,to_date('07-01-00','DD-MM-RR'),'07:00','Parc','voiture',2);
Insert into DRIVINGSCHOOL.SEANCE (ID_SEANCE,IMMATRICULE,ID_CLIENT,ID_MONITEUR,DATE_SEANCE,HEURE_DEBUT,TYPE,APPAREIL,DUREE) values (4,'AZERTY',5,2,to_date('05-11-25','DD-MM-RR'),'09:36','code','pc',2);
Insert into DRIVINGSCHOOL.SEANCE (ID_SEANCE,IMMATRICULE,ID_CLIENT,ID_MONITEUR,DATE_SEANCE,HEURE_DEBUT,TYPE,APPAREIL,DUREE) values (999,'AZERTY',5,2,to_date('01-01-00','DD-MM-RR'),'00:00','code','pc',2);
Insert into DRIVINGSCHOOL.SEANCE (ID_SEANCE,IMMATRICULE,ID_CLIENT,ID_MONITEUR,DATE_SEANCE,HEURE_DEBUT,TYPE,APPAREIL,DUREE) values (123,'AZERTY',5,2,to_date('07-11-25','DD-MM-RR'),'16:39','Conduite','voiture',6);
Insert into DRIVINGSCHOOL.SEANCE (ID_SEANCE,IMMATRICULE,ID_CLIENT,ID_MONITEUR,DATE_SEANCE,HEURE_DEBUT,TYPE,APPAREIL,DUREE) values (1,'abc',13,2,to_date('08-11-25','DD-MM-RR'),'12:10','code','pc',5);
REM INSERTING into DRIVINGSCHOOL.VEHICULE
SET DEFINE OFF;
Insert into DRIVINGSCHOOL.VEHICULE (IMMATRICULE,MODELE,TYPE_VEHICULE,TRANSMISSION,ETAT,DATE_ASSURENCE) values ('tuis123','mm','? Camion','?? Automatique','?Disponible',to_date('06-11-25','DD-MM-RR'));
Insert into DRIVINGSCHOOL.VEHICULE (IMMATRICULE,MODELE,TYPE_VEHICULE,TRANSMISSION,ETAT,DATE_ASSURENCE) values ('abc','kiya','? Voiture','? Manuelle','?Disponible',to_date('03-11-25','DD-MM-RR'));
Insert into DRIVINGSCHOOL.VEHICULE (IMMATRICULE,MODELE,TYPE_VEHICULE,TRANSMISSION,ETAT,DATE_ASSURENCE) values ('imaaa','ibiza','? Voiture','?? Automatique','?Disponible',to_date('19-11-25','DD-MM-RR'));
Insert into DRIVINGSCHOOL.VEHICULE (IMMATRICULE,MODELE,TYPE_VEHICULE,TRANSMISSION,ETAT,DATE_ASSURENCE) values ('AZERTY','polo','? Voiture','?? Automatique','?Disponible',to_date('01-01-00','DD-MM-RR'));
Insert into DRIVINGSCHOOL.VEHICULE (IMMATRICULE,MODELE,TYPE_VEHICULE,TRANSMISSION,ETAT,DATE_ASSURENCE) values ('KKK','mm','?? Moto','?? Automatique','?Indisponible',to_date('01-01-00','DD-MM-RR'));
Insert into DRIVINGSCHOOL.VEHICULE (IMMATRICULE,MODELE,TYPE_VEHICULE,TRANSMISSION,ETAT,DATE_ASSURENCE) values ('ZED123AZZZ','pejo','? Voiture','? Manuelle','?Disponible',to_date('11-11-25','DD-MM-RR'));
Insert into DRIVINGSCHOOL.VEHICULE (IMMATRICULE,MODELE,TYPE_VEHICULE,TRANSMISSION,ETAT,DATE_ASSURENCE) values ('123TU1234','Peugeot 208','? Voiture','? Manuelle','?Disponible',to_date('01-01-25','DD-MM-RR'));
Insert into DRIVINGSCHOOL.VEHICULE (IMMATRICULE,MODELE,TYPE_VEHICULE,TRANSMISSION,ETAT,DATE_ASSURENCE) values ('200TU5678','Renault Clio','? Voiture','? Manuelle','?Disponible',to_date('01-06-24','DD-MM-RR'));
Insert into DRIVINGSCHOOL.VEHICULE (IMMATRICULE,MODELE,TYPE_VEHICULE,TRANSMISSION,ETAT,DATE_ASSURENCE) values ('PPP','polo','? Voiture','?? Automatique','?Disponible',to_date('01-01-00','DD-MM-RR'));
Insert into DRIVINGSCHOOL.VEHICULE (IMMATRICULE,MODELE,TYPE_VEHICULE,TRANSMISSION,ETAT,DATE_ASSURENCE) values ('ROJAAA','golf6','?? Moto','?? Automatique','?Indisponible',to_date('01-01-00','DD-MM-RR'));
--------------------------------------------------------
--  DDL for Index PK_CIRCUIT
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVINGSCHOOL"."PK_CIRCUIT" ON "DRIVINGSCHOOL"."CIRCUIT" ("ID_CIRCUIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007357
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVINGSCHOOL"."SYS_C007357" ON "DRIVINGSCHOOL"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007355
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVINGSCHOOL"."SYS_C007355" ON "DRIVINGSCHOOL"."EMPLOYE" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007356
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVINGSCHOOL"."SYS_C007356" ON "DRIVINGSCHOOL"."MONITEUR" ("ID_MONITEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007363
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVINGSCHOOL"."SYS_C007363" ON "DRIVINGSCHOOL"."PLANIFIER" ("ID_EMPLOYE", "ID_SEANCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007359
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVINGSCHOOL"."SYS_C007359" ON "DRIVINGSCHOOL"."SEANCE" ("ID_SEANCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007358
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVINGSCHOOL"."SYS_C007358" ON "DRIVINGSCHOOL"."VEHICULE" ("IMMATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CIRCUIT
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."CIRCUIT" ADD CONSTRAINT "PK_CIRCUIT" PRIMARY KEY ("ID_CIRCUIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DRIVINGSCHOOL"."CIRCUIT" MODIFY ("ID_CIRCUIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."CLIENT" ADD PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."EMPLOYE" ADD PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MONITEUR
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."MONITEUR" ADD PRIMARY KEY ("ID_MONITEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLANIFIER
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."PLANIFIER" ADD PRIMARY KEY ("ID_EMPLOYE", "ID_SEANCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEANCE
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."SEANCE" ADD PRIMARY KEY ("ID_SEANCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VEHICULE
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."VEHICULE" ADD PRIMARY KEY ("IMMATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CIRCUIT
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."CIRCUIT" ADD CONSTRAINT "FK_CIRCUIT" FOREIGN KEY ("IMMATRICULE")
	  REFERENCES "DRIVINGSCHOOL"."VEHICULE" ("IMMATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLANIFIER
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."PLANIFIER" ADD CONSTRAINT "FK_PLANIFIER_EMPLOYE" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "DRIVINGSCHOOL"."EMPLOYE" ("ID_EMPLOYE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DRIVINGSCHOOL"."PLANIFIER" ADD CONSTRAINT "FK_PLANIFIER_SEANCE" FOREIGN KEY ("ID_SEANCE")
	  REFERENCES "DRIVINGSCHOOL"."SEANCE" ("ID_SEANCE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEANCE
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."SEANCE" ADD CONSTRAINT "FK_SEANCE_CLIENT" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "DRIVINGSCHOOL"."CLIENT" ("ID_CLIENT") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DRIVINGSCHOOL"."SEANCE" ADD CONSTRAINT "FK_SEANCE_MONITEUR" FOREIGN KEY ("ID_MONITEUR")
	  REFERENCES "DRIVINGSCHOOL"."MONITEUR" ("ID_MONITEUR") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DRIVINGSCHOOL"."SEANCE" ADD CONSTRAINT "FK_SEANCE_VEHICULE" FOREIGN KEY ("IMMATRICULE")
	  REFERENCES "DRIVINGSCHOOL"."VEHICULE" ("IMMATRICULE") ON DELETE CASCADE ENABLE;
