--------------------------------------------------------
--  Fichier créé - mardi-novembre-04-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "DRIVINGSCHOOL"."CLIENT" 
   (	"ID_CLIENT" NUMBER(*,0), 
	"NOM_CLIENT" VARCHAR2(50 BYTE), 
	"PRENOM_CLIENT" VARCHAR2(50 BYTE), 
	"CIN" VARCHAR2(20 BYTE), 
	"DATE_NAISSANCE" DATE, 
	"ADRESSE" VARCHAR2(100 BYTE), 
	"TELEPHONE_CLIENT" VARCHAR2(50 BYTE), 
	"CODE_QR" VARCHAR2(50 BYTE), 
	"LOCALISATION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "DRIVINGSCHOOL"."EMPLOYE" 
   (	"ID_EMPLOYE" NUMBER(*,0), 
	"NOM_EMPLOYE" VARCHAR2(50 BYTE), 
	"PRENOM_EMPLOYE" VARCHAR2(50 BYTE), 
	"POSTE" VARCHAR2(50 BYTE), 
	"MOT_DE_PASSE" VARCHAR2(50 BYTE), 
	"CODE_SECURITE" VARCHAR2(50 BYTE), 
	"TELEPHONE" VARCHAR2(50 BYTE), 
	"DATE_EMBAUCHE" DATE, 
	"STATUS_EMPLOYE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MONITEUR
--------------------------------------------------------

  CREATE TABLE "DRIVINGSCHOOL"."MONITEUR" 
   (	"ID_MONITEUR" NUMBER(*,0), 
	"CIN_MONITEUR" VARCHAR2(20 BYTE), 
	"NOM_MONITEUR" VARCHAR2(20 BYTE), 
	"PRENOM_MONITEUR" VARCHAR2(20 BYTE), 
	"TEL_MONITEUR" NUMBER(*,0), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PERMIS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PLANIFIER
--------------------------------------------------------

  CREATE TABLE "DRIVINGSCHOOL"."PLANIFIER" 
   (	"ID_EMPLOYE" NUMBER(*,0), 
	"ID_SEANCE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SEANCE
--------------------------------------------------------

  CREATE TABLE "DRIVINGSCHOOL"."SEANCE" 
   (	"ID_SEANCE" NUMBER(*,0), 
	"IMMATRICULE" VARCHAR2(50 BYTE), 
	"ID_CLIENT" NUMBER(*,0), 
	"ID_MONITEUR" NUMBER(*,0), 
	"DATE_SEANCE" DATE, 
	"HEURE_DEBUT" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"APPAREIL" VARCHAR2(20 BYTE), 
	"DUREE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEHICULE
--------------------------------------------------------

  CREATE TABLE "DRIVINGSCHOOL"."VEHICULE" 
   (	"IMMATRICULE" VARCHAR2(50 BYTE), 
	"MODELE" VARCHAR2(20 BYTE), 
	"TYPE_VEHICULE" VARCHAR2(20 BYTE), 
	"TRANSMISSION" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"DATE_ASSURENCE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DRIVINGSCHOOL.CLIENT
SET DEFINE OFF;
Insert into DRIVINGSCHOOL.CLIENT (ID_CLIENT,NOM_CLIENT,PRENOM_CLIENT,CIN,DATE_NAISSANCE,ADRESSE,TELEPHONE_CLIENT,CODE_QR,LOCALISATION) values (12,null,null,null,null,null,null,null,null);
Insert into DRIVINGSCHOOL.CLIENT (ID_CLIENT,NOM_CLIENT,PRENOM_CLIENT,CIN,DATE_NAISSANCE,ADRESSE,TELEPHONE_CLIENT,CODE_QR,LOCALISATION) values (5,'moemen','kochbati','1452222',to_date('15-10-15','DD-MM-RR'),'sidi_thbet','12457896','abcdef','azerty');
REM INSERTING into DRIVINGSCHOOL.EMPLOYE
SET DEFINE OFF;
REM INSERTING into DRIVINGSCHOOL.MONITEUR
SET DEFINE OFF;
Insert into DRIVINGSCHOOL.MONITEUR (ID_MONITEUR,CIN_MONITEUR,NOM_MONITEUR,PRENOM_MONITEUR,TEL_MONITEUR,EMAIL,PERMIS) values (5,null,null,null,null,null,null);
Insert into DRIVINGSCHOOL.MONITEUR (ID_MONITEUR,CIN_MONITEUR,NOM_MONITEUR,PRENOM_MONITEUR,TEL_MONITEUR,EMAIL,PERMIS) values (2,'gfdsqaz','ryhem','mejri',21365478,'mmmffnhà@fjjff.com','b');
REM INSERTING into DRIVINGSCHOOL.PLANIFIER
SET DEFINE OFF;
REM INSERTING into DRIVINGSCHOOL.SEANCE
SET DEFINE OFF;
Insert into DRIVINGSCHOOL.SEANCE (ID_SEANCE,IMMATRICULE,ID_CLIENT,ID_MONITEUR,DATE_SEANCE,HEURE_DEBUT,TYPE,APPAREIL,DUREE) values (55,null,null,null,to_date('04-11-25','DD-MM-RR'),'04-NOV-25','code','pc',2);
Insert into DRIVINGSCHOOL.SEANCE (ID_SEANCE,IMMATRICULE,ID_CLIENT,ID_MONITEUR,DATE_SEANCE,HEURE_DEBUT,TYPE,APPAREIL,DUREE) values (12,'abc',5,2,to_date('01-01-00','DD-MM-RR'),'00:00','code','pc',2);
Insert into DRIVINGSCHOOL.SEANCE (ID_SEANCE,IMMATRICULE,ID_CLIENT,ID_MONITEUR,DATE_SEANCE,HEURE_DEBUT,TYPE,APPAREIL,DUREE) values (3,null,null,null,to_date('04-11-25','DD-MM-RR'),'04-NOV-25',null,'04-NOV-25',8);
Insert into DRIVINGSCHOOL.SEANCE (ID_SEANCE,IMMATRICULE,ID_CLIENT,ID_MONITEUR,DATE_SEANCE,HEURE_DEBUT,TYPE,APPAREIL,DUREE) values (1,null,null,null,to_date('04-11-25','DD-MM-RR'),'04-NOV-25','code','pc',8);
Insert into DRIVINGSCHOOL.SEANCE (ID_SEANCE,IMMATRICULE,ID_CLIENT,ID_MONITEUR,DATE_SEANCE,HEURE_DEBUT,TYPE,APPAREIL,DUREE) values (5,'abc',5,2,to_date('01-01-00','DD-MM-RR'),'00:00','code','pc',2);
REM INSERTING into DRIVINGSCHOOL.VEHICULE
SET DEFINE OFF;
Insert into DRIVINGSCHOOL.VEHICULE (IMMATRICULE,MODELE,TYPE_VEHICULE,TRANSMISSION,ETAT,DATE_ASSURENCE) values ('tuis123',null,null,null,null,null);
Insert into DRIVINGSCHOOL.VEHICULE (IMMATRICULE,MODELE,TYPE_VEHICULE,TRANSMISSION,ETAT,DATE_ASSURENCE) values ('abc','kiya','famliyal','ryhem','nevau',to_date('03-11-25','DD-MM-RR'));
Insert into DRIVINGSCHOOL.VEHICULE (IMMATRICULE,MODELE,TYPE_VEHICULE,TRANSMISSION,ETAT,DATE_ASSURENCE) values ('imaaa','ibiza','hor','hhh','oui',to_date('19-11-25','DD-MM-RR'));
Insert into DRIVINGSCHOOL.VEHICULE (IMMATRICULE,MODELE,TYPE_VEHICULE,TRANSMISSION,ETAT,DATE_ASSURENCE) values ('AZERTY','pc','? Voiture','?? Automatique','?Disponible',to_date('01-01-00','DD-MM-RR'));
Insert into DRIVINGSCHOOL.VEHICULE (IMMATRICULE,MODELE,TYPE_VEHICULE,TRANSMISSION,ETAT,DATE_ASSURENCE) values ('AAA','zzzz','? Voiture','? Manuelle','?Disponible',to_date('07-11-25','DD-MM-RR'));
Insert into DRIVINGSCHOOL.VEHICULE (IMMATRICULE,MODELE,TYPE_VEHICULE,TRANSMISSION,ETAT,DATE_ASSURENCE) values ('RRR','bmw','? Voiture','? Manuelle','?Disponible',to_date('09-01-25','DD-MM-RR'));
--------------------------------------------------------
--  DDL for Index SYS_C007357
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVINGSCHOOL"."SYS_C007357" ON "DRIVINGSCHOOL"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007355
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVINGSCHOOL"."SYS_C007355" ON "DRIVINGSCHOOL"."EMPLOYE" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007356
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVINGSCHOOL"."SYS_C007356" ON "DRIVINGSCHOOL"."MONITEUR" ("ID_MONITEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007363
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVINGSCHOOL"."SYS_C007363" ON "DRIVINGSCHOOL"."PLANIFIER" ("ID_EMPLOYE", "ID_SEANCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007359
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVINGSCHOOL"."SYS_C007359" ON "DRIVINGSCHOOL"."SEANCE" ("ID_SEANCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007358
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRIVINGSCHOOL"."SYS_C007358" ON "DRIVINGSCHOOL"."VEHICULE" ("IMMATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."CLIENT" ADD PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."EMPLOYE" ADD PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MONITEUR
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."MONITEUR" ADD PRIMARY KEY ("ID_MONITEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLANIFIER
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."PLANIFIER" ADD PRIMARY KEY ("ID_EMPLOYE", "ID_SEANCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEANCE
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."SEANCE" ADD PRIMARY KEY ("ID_SEANCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VEHICULE
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."VEHICULE" ADD PRIMARY KEY ("IMMATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLANIFIER
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."PLANIFIER" ADD CONSTRAINT "FK_PLANIFIER_EMPLOYE" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "DRIVINGSCHOOL"."EMPLOYE" ("ID_EMPLOYE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DRIVINGSCHOOL"."PLANIFIER" ADD CONSTRAINT "FK_PLANIFIER_SEANCE" FOREIGN KEY ("ID_SEANCE")
	  REFERENCES "DRIVINGSCHOOL"."SEANCE" ("ID_SEANCE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEANCE
--------------------------------------------------------

  ALTER TABLE "DRIVINGSCHOOL"."SEANCE" ADD CONSTRAINT "FK_SEANCE_CLIENT" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "DRIVINGSCHOOL"."CLIENT" ("ID_CLIENT") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DRIVINGSCHOOL"."SEANCE" ADD CONSTRAINT "FK_SEANCE_MONITEUR" FOREIGN KEY ("ID_MONITEUR")
	  REFERENCES "DRIVINGSCHOOL"."MONITEUR" ("ID_MONITEUR") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DRIVINGSCHOOL"."SEANCE" ADD CONSTRAINT "FK_SEANCE_VEHICULE" FOREIGN KEY ("IMMATRICULE")
	  REFERENCES "DRIVINGSCHOOL"."VEHICULE" ("IMMATRICULE") ON DELETE CASCADE ENABLE;
